version: "3.1"
services:
  db:
    build: .
    container_name: artofpostgres
    environment:
      HOST_IP: host.docker.internal
      POSTGRES_PASSWORD: password
    ports:
      - 5440:5432
    restart: always
    volumes:
      - ./scripts:/scripts:ro
      - ./data:/data:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
